name: Build and deploy the frontend app
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - 'website/**'
permissions:
    contents: write
              
jobs:
    build:
        name: Build the frontend app
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source code
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.GH_TOKEN }}

            -   name: Use Node.js 16
                uses: actions/setup-node@v3
                with:
                    node-version: 16
                    cache: 'npm'

            -   name: Install dependencies
                run: |
                    cd website
                    npm ci
                    cd ..

            -   name: Build the app
                run: |
                    cd website
                    npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: website/build